"""Regenerate docs/atlas/CONTENT_COVERAGE.md from the Learn map and the atlas registry. Run: python tools/atlas_coverage.py"""
import json, datetime
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
graph = json.loads((ROOT / "content/learn/graph.json").read_text(encoding="utf-8"))
con = json.loads((ROOT / "content/atlas/concepts.json").read_text(encoding="utf-8"))
by_map = {c["mapId"]: c for c in con["concepts"] if c.get("mapId")}
status = Counter(c["status"] for c in con["concepts"])
ideas = graph["ideas"]
done = [i for i in ideas if i["id"] in by_map]
rows = "\n".join(
    f'| `{i["id"]}` | {i["label"]} | {i["cluster"]} | ' + (f'yes, as `{by_map[i["id"]]["id"]}`' if i["id"] in by_map else "pending") + " |"
    for i in ideas)
out = f"""# Content coverage · {datetime.date.today().isoformat()}

Generated by `python tools/atlas_coverage.py` from `content/learn/graph.json` ({len(ideas)} ideas) and `content/atlas/concepts.json`.

**Atlas registry:** {len(con["concepts"])} concepts, content version {con["version"]}. Every one is drawn in a scene (as an object or a clickable part of one) with three depths, a metaphor limit, a failure mode, a boundary note and SHAMS moves.
- {len(by_map)} map to Learn-map ids; {len(con["concepts"]) - len(by_map)} are specific to the atlas.
- Status: {status["source-checked"]} source-checked, {status["editorial"]} editorial (teaching judgment, no external claim), {status["needs-review"]} needs review.

**Learn-map coverage:** {len(done)} of {len(ideas)} map ideas illustrated in the atlas; {len(ideas) - len(done)} pending.

| Map id | Label | Cluster | Illustrated in the atlas |
|---|---|---|---|
{rows}
"""
(ROOT / "docs/atlas/CONTENT_COVERAGE.md").write_text(out, encoding="utf-8")
print(f"coverage: {len(done)}/{len(ideas)} map ideas, {len(con['concepts'])} concepts")
