# One card per post. Key = post slug (filename without date and .md).
CARDS = {
"the-demo-is-never-the-hard-part": dict(layout="contrast", dark=True, eyebrow="Agentic AI",
    text="Most agent demos work. Most agent systems don't.",
    cols=[("What gets demoed",["The model answering well","A clean happy path","One user, one session"]),
          ("What gets shipped",["Agent boundaries and handoffs","Grounding with provenance","An evaluation harness","Blast radius controls"])]),
"1-000-tenants-and-a-problem-you-can-t-reproduce": dict(layout="bignum", dark=True, eyebrow="Multi-tenant SaaS",
    num="1,000+", text="tenant databases, one complaint nobody could reproduce, and a fix that was written rules, not a bigger tier."),
"4-5m-without-looking-at-a-price-sheet": dict(layout="bignum", dark=False, eyebrow="Assessment",
    num="$4.5M", text="in cost avoidance, without a single price sheet. The savings weren't in negotiating. They were in noticing."),
"ask-to-see-the-evaluation-harness": dict(layout="statement", dark=False, eyebrow="One question",
    text="“Can you show me your evaluation harness?”", sub="If the answer is a pause, you're looking at a prototype wearing production clothes."),
"root-cause-before-remediation": dict(layout="statement", dark=True, eyebrow="Escalations",
    text="Root cause first. Remediation second.", sub="Resize before you understand and you have the same problem at a higher bill."),
"the-dashboard-that-got-applause": dict(layout="statement", dark=False, eyebrow="Foundations",
    text="Build the engine before you shape the body.", sub="Dashboards that get applause are the cheapest thing to build and the most expensive thing to keep."),
"the-agent-inherits-the-user-s-permissions": dict(layout="statement", dark=True, eyebrow="Security",
    text="The agent inherits the user's permissions, and never exceeds them.", sub="Governance isn't the brake. It's what lets you take your foot off it."),
"where-i-put-the-human": dict(layout="numbered", dark=False, eyebrow="Healthcare",
    text="Two rules that held a clinical system together",
    items=["Never destroy the source. The original evidence stays, alongside anything derived from it.",
           "Never blur what was observed with what was inferred. Provenance is the difference between a record and a rumour."]),
# ---- next 18 ----
"a-landing-zone-is-a-political-document": dict(layout="statement", dark=True, eyebrow="Cloud platforms",
    text="A landing zone is a political document that happens to be implemented in Azure.", sub="Ownership, funding, exceptions, review. The Bicep sits underneath that page."),
"the-cheapest-migration-is-the-one-you-skip": dict(layout="bignum", dark=False, eyebrow="Migration",
    num="1/3", text="of the application estate had no owner. You don't migrate that. You retire it, or you ask the question out loud first."),
"three-questions-before-any-ai-project": dict(layout="numbered", dark=True, eyebrow="Before the model",
    text="Three questions before any AI project",
    items=["Who is accountable when it's wrong?","What is it allowed to see, per user, enforced by the platform?","What does a run cost at ten times the volume?"]),
"cost-per-run-is-an-architecture-decision": dict(layout="contrast", dark=False, eyebrow="Economics",
    text="A license costs the same whether people use it or not. An agent costs more the better it works.",
    cols=[("Fixed cost software",["Adoption is the goal","Cost is flat","Finance sees it once"]),
          ("Agentic systems",["Adoption is the goal","Cost scales with success","Token budgets per run","Model routing and caching","Cost next to quality on one dashboard"])]),
"where-deals-actually-die": dict(layout="statement", dark=True, eyebrow="Partner channel",
    text="Deals rarely die in the sales meeting. They die in the gap between the slide and the delivery calendar.", sub="The most expensive sentence in enterprise technology is “we'll figure that out in delivery.”"),
"retrieval-is-not-memory": dict(layout="contrast", dark=True, eyebrow="Agent design",
    text="Retrieval is not memory.",
    cols=[("Retrieval",["Looked up when needed","Source stays governed","Changes when the source changes","Provenance attached"]),
          ("Memory",["A second copy","Nobody governs it","Nobody knows when it's stale","The agent prefers it anyway"])]),
"write-the-runbook-before-the-incident": dict(layout="statement", dark=False, eyebrow="Resilience",
    text="Three confident answers about the failover. None matched what was configured.", sub="Assumed posture and actual posture drift apart quietly. Write it down and test it."),
"fabric-changed-the-question": dict(layout="contrast", dark=False, eyebrow="Data platforms",
    text="Fabric changed the question.",
    cols=[("Before",["“Where is the data?”","Catalogues and tribal knowledge","Every extract is a new place","Never really ends"]),
          ("After",["“Who owns this layer?”","Bronze: whoever ingests","Silver: the data team, with contracts","Gold: the people who consume it"])]),
"idempotent-or-it-didn-t-happen": dict(layout="statement", dark=True, eyebrow="Agent writes",
    text="Idempotent, or it doesn't get a tool.", sub="The demo never shows the retry. Production always does."),
"a-migration-is-a-change-of-ownership": dict(layout="numbered", dark=False, eyebrow="Migration",
    text="A migration is a change of ownership. Cutover is one milestone inside it.",
    items=["Who owns the bill, and from what date","Who owns change, and how it's made safely","Who owns the 3am page","When each handover happens. A date, not “after go-live”"]),
"the-cost-of-seeing-everything": dict(layout="statement", dark=True, eyebrow="Security operations",
    text="“Send everything to Sentinel” is a bill, not a security strategy.", sub="Start from what you need to detect. Trace backwards to the sources that feed it."),
"small-models-big-boundaries": dict(layout="contrast", dark=False, eyebrow="Model routing",
    text="Small models, big boundaries.",
    cols=[("Small, fast model",["Classify the request","Extract the fields","Format the answer","Pick the tool"]),
          ("Frontier model",["Reconcile conflicting evidence","Plan a multi-step task","Decide “I can't do this safely”"])]),
"the-pilot-that-never-ends": dict(layout="statement", dark=True, eyebrow="AI pilots",
    text="Most AI pilots don't fail. They just never end.", sub="Exit criteria go in the first document, before the architecture. Both outcomes are wins."),
"what-building-on-aws-taught-me-about-boring": dict(layout="numbered", dark=False, eyebrow="Solo operations",
    text="What keeps a platform running when you're the whole team",
    items=["Managed services wherever one exists","One deployment path, scripted, used every time","Backups tested by restoring them","A cost alarm set lower than you think you need","Logs you actually read"]),
"the-slide-nobody-wants-to-see": dict(layout="statement", dark=False, eyebrow="Assessments",
    text="In every assessment there's one slide people would rather not see.", sub="The dependency map. Every application, integration, identity, vendor, and data flow, on one page."),
"why-did-it-do-that": dict(layout="contrast", dark=True, eyebrow="Observability",
    text="Logs tell you what an agent did. A trace tells you why.",
    cols=[("Logs",["Tool was called","Response came back","Answer was returned"]),
          ("Traces",["The plan it formed","What it retrieved, and ignored","Each decision and the rejected alternative","The cost of every step"])]),
"boring-is-a-feature": dict(layout="statement", dark=False, eyebrow="Architecture",
    text="The platform should be dull. The product on top of it should be interesting.", sub="Most teams get that backwards."),
"what-i-m-carrying-into-next-year": dict(layout="numbered", dark=True, eyebrow="Year end",
    text="Three things I'm carrying into next year",
    items=["Write the rules down.","Keep the human where the judgment is.","Build the foundation before the feature."]),
}

# ---- Dec 17, 2026 through Apr 29, 2027 ----
CARDS.update({
"read-the-invoice-before-the-architecture-review": dict(layout="statement", dark=True, eyebrow="Cloud cost",
    text="The cloud bill is the most honest architecture diagram an organisation has.", sub="Diagrams show intent. The invoice shows what was actually built."),
"show-me-the-last-three-incidents": dict(layout="numbered", dark=False, eyebrow="First week",
    text="What three incidents tell you that the architecture deck can't",
    items=["Where the real dependencies are","Who actually understands the system","What the team believes that isn't true anymore","Which part of the design exists only on the slide"]),
"tool-calls-are-an-api-contract": dict(layout="numbered", dark=True, eyebrow="Agent tools",
    text="Every tool is a versioned API contract",
    items=["Typed input, validated before execution","Typed output the next step can trust","A description written for the model","Versioned, because old prompts keep calling","Permission scope inherited from the user"]),
"someone-else-s-bug-is-your-outage": dict(layout="statement", dark=False, eyebrow="Multi-tenant",
    text="A customer you've never met can take down the customer who pays you the most.", sub="The answer has never been more capacity. It's isolation, decided on purpose."),
"an-assessment-is-not-a-sales-deck": dict(layout="contrast", dark=True, eyebrow="Solution assessment",
    text="The good assessments told the customer something they didn't want to hear.",
    cols=[("A sales deck",["Starts from the product","Works backwards to evidence","Goes in a drawer"]),
          ("An assessment",["Measures before it recommends","Separates findings from opinions","Names an owner for every gap"])]),
"prompts-are-config-not-code": dict(layout="statement", dark=True, eyebrow="Prompt management",
    text="Prompts are configuration, and most teams manage them like sticky notes.", sub="Version control. Harness before merge. A version id in every trace. Rollback in one commit."),
"a-dr-plan-you-ve-never-run-is-a-rumour": dict(layout="statement", dark=False, eyebrow="Resilience",
    text="Until you've run it, a DR plan is a rumour.", sub="A well-formatted rumour with an approval signature on it."),
"the-success-metric-that-actually-mattered": dict(layout="statement", dark=True, eyebrow="Customer success",
    text="Not “is it deployed.” Is it theirs.", sub="Workloads in production, owned by the customer's own team, without us on the call."),
"where-rag-quietly-fails": dict(layout="numbered", dark=False, eyebrow="Retrieval",
    text="Four ways an index goes wrong without telling you",
    items=["The index is stale","The permissions drifted","The chunks lost their context","The citations point at nothing"]),
"naming-is-an-architecture-decision": dict(layout="statement", dark=False, eyebrow="Landing zones",
    text="Every hard question in cloud operations resolves to a lookup against names and tags.", sub="Cost. Ownership. Scope. Lifecycle. Compliance. If the name doesn't carry it, a human has to."),
"how-a-tenant-earns-the-next-tier": dict(layout="contrast", dark=True, eyebrow="Tiering",
    text="Two ways a tenant gets upgraded. Only one scales.",
    cols=[("Loudest customer",["Cost unrelated to need","Support can't explain the estate","Every escalation reopens the argument"]),
          ("Written criteria",["Sustained utilisation over a window","A contractual SLA","An enterprise workload profile","Applied on a Tuesday, without a meeting"])]),
"every-agent-needs-an-off-switch": dict(layout="bignum", dark=True, eyebrow="Agent safety",
    num="10s", text="An off switch takes ten seconds. A rollback takes ten minutes if everything goes well. Agents fail fast, repetitive, and confident."),
"five-languages-one-patient": dict(layout="numbered", dark=False, eyebrow="Clinical intake",
    text="The machine did the reading. People did the deciding.",
    items=["Extraction produces a candidate, never a fact","Below threshold goes to a human, in the original language","Name matching proposes. It never merges.","The source document stays immutable, forever"]),
"the-partner-who-said-no": dict(layout="statement", dark=True, eyebrow="Partner channel",
    text="Saying no to the wrong version of the work is how you earn the right to do the right version.", sub="They lost that deal. They won the next three."),
"data-contracts-before-dashboards": dict(layout="statement", dark=False, eyebrow="Data platforms",
    text="A dashboard built on an undocumented table is a promise nobody agreed to keep.", sub="Schema, grain, refresh, quality checks, and a process for change. Signed by the producer."),
"least-privilege-for-machines": dict(layout="contrast", dark=True, eyebrow="Identity",
    text="People get least privilege reviews. Service principals get created once.",
    cols=[("Human identities",["Joiners, movers, leavers","Access reviews","Just-in-time elevation"]),
          ("Machine identities",["Created on day one","Contributor on the subscription","Never looked at again","Now an agent runs on top of it"])]),
"semantic-models-are-a-contract-too": dict(layout="bignum", dark=False, eyebrow="Governed metrics",
    num="3", text="definitions of revenue is not a data platform. It's three opinions with charts attached."),
"a-human-in-the-loop-is-a-ui-problem": dict(layout="statement", dark=True, eyebrow="Review design",
    text="If the review screen is bad, the human stops reviewing and starts approving.", sub="A human in the loop is only a control if the human can exercise judgment."),
"the-regions-nobody-remembers-choosing": dict(layout="numbered", dark=False, eyebrow="Region choice",
    text="One decision that looks trivial on day one and turns out to be load-bearing",
    items=["Your latency floor","Which services and SKUs exist for you","Whether failover has somewhere to go","Whether you're compliant with the residency clause","Whether you can ever move"]),
"audit-logs-are-for-the-future-you": dict(layout="numbered", dark=True, eyebrow="Audit design",
    text="Design the audit trail for the question you can't predict yet",
    items=["Append-only, for everyone, including admins","Actor, subject, before, after, reason","Automated actions logged as the system, with who authorised it","Inferences logged separately from observations","Reads of sensitive records are events too"]),
"what-the-model-may-not-say": dict(layout="statement", dark=False, eyebrow="Provenance rules",
    text="The canonical text is never generated. The model may reference it, never paraphrase it as if it were the source.", sub="Fewer assertions, more citations, and a hard line the model can't cross."),
"three-signs-a-platform-team-is-losing": dict(layout="numbered", dark=True, eyebrow="Platform teams",
    text="Platform teams don't fail loudly",
    items=["Exceptions become the process","Shadow environments appear","Everyone is waiting"]),
"predictable-beats-clever": dict(layout="statement", dark=True, eyebrow="Production agents",
    text="An agent that does the same thing every time is worth more than one that occasionally does something brilliant.", sub="Clever is for the prototype. Predictable is for the system people rely on."),
"say-the-honest-number": dict(layout="contrast", dark=False, eyebrow="Estimates",
    text="The range is the honest number. The point estimate is a wish.",
    cols=[("What the room wants",["“Six months”","Fits the slide","Fits the fiscal year","Month seven: explaining"]),
          ("What's true",["Four to nine months","Three named unknowns","What resolving the biggest one costs","Month seven: which assumption broke"])]),
"backups-are-not-disaster-recovery": dict(layout="statement", dark=True, eyebrow="Recovery",
    text="Having backups tells you your data exists somewhere. It tells you nothing about how long it takes to be a system again.", sub="RPO. RTO. Dependencies. Access. Proof."),
"what-a-solutions-architect-actually-does": dict(layout="statement", dark=False, eyebrow="The job",
    text="The architect owns the call between the people who pay and the people who build.", sub="The diagram is just the receipt."),
"structured-outputs-are-the-new-api": dict(layout="contrast", dark=True, eyebrow="Model output",
    text="Free text from a model is a demo. A validated object is a system.",
    cols=[("Free text",["Looks right","Assumed right","Nobody checked","Fails downstream"]),
          ("Structured output",["A schema per output","Validated before use","Retry with the validation error","Tested without a model in the loop"])]),
"the-cost-alarm-i-set-too-low": dict(layout="bignum", dark=False, eyebrow="Cost signals",
    num="3×", text="the cost alarm on my own platform has paid for itself. Set it at surprising, not catastrophic."),
"designing-the-queue": dict(layout="numbered", dark=True, eyebrow="Human in the loop",
    text="The most important screen in the product is the queue",
    items=["Priority by consequence, not arrival","A service level per item type, visible","One owner per item; unclaimed items age visibly","Reason codes that feed the evaluation set","Nothing leaves without a person's name on it"]),
"don-t-let-the-pilot-pick-the-platform": dict(layout="statement", dark=False, eyebrow="AI pilots",
    text="Pilots make platform decisions by accident.", sub="Whatever was convenient in week two becomes load-bearing for five years."),
"feature-flags-for-models": dict(layout="numbered", dark=True, eyebrow="Model upgrades",
    text="A model version change is a production deploy",
    items=["Model id behind a flag, per workflow","Full harness first: accuracy, groundedness, cost, latency","A slice of traffic, traces tagged by version","Rollback is flipping the flag"]),
"sequencing-is-the-strategy": dict(layout="numbered", dark=False, eyebrow="Order of operations",
    text="Controls before workloads, every time",
    items=["Identity and access boundaries","The data platform, with ownership and policy","Monitoring wired to detections someone maintains","Workloads, onto a foundation that knows how to say no"]),
"who-owns-the-prompt": dict(layout="contrast", dark=True, eyebrow="Ownership",
    text="Ask who owns the system prompt and watch the room go quiet.",
    cols=[("What a prompt encodes",["Product policy","Legal exposure","Brand voice","Risk posture"]),
          ("Who owns which part",["Engineering: the mechanics","Product: the behaviour","Risk: the boundaries","One name for the whole"])]),
"say-it-in-one-page": dict(layout="statement", dark=False, eyebrow="Decisions",
    text="If the decision needs a deck, the decision isn't ready.", sub="One page. A recommendation, a name, a date. The deck is the appendix."),
"what-i-d-tell-myself-in-september": dict(layout="numbered", dark=True, eyebrow="Seven months in",
    text="What I'd tell myself in September",
    items=["The specific posts did better than the general ones","The comments were the real content","Consistency was the whole trick","The themes didn't change. They got more evidence."]),
})
