# One card per post. Key = post slug (filename without date and .md).
CARDS = {
"the-demo-is-never-the-hard-part": dict(layout="contrast", dark=True, eyebrow="Agentic AI",
    text="Most agent demos work. Most agent systems don't.",
    cols=[("What gets demoed",["The model answering well","A clean happy path","One user, one session"]),
          ("What gets shipped",["Agent boundaries and handoffs","Grounding with provenance","An evaluation harness","Blast radius controls"])]),
"1-000-tenants-and-a-problem-you-can-t-reproduce": dict(layout="bignum", dark=True, eyebrow="Multi-tenant SaaS",
    num="1,000+", text="tenant databases, one complaint nobody could reproduce, and a fix that was written rules, not a bigger tier."),
"4-5m-without-looking-at-a-price-sheet": dict(layout="bignum", dark=False, eyebrow="Assessment",
    num="$4.5M", text="in cost avoidance, without a single price sheet. The savings weren't in negotiating. They were in noticing."),
"ask-to-see-the-evaluation-harness": dict(layout="statement", dark=False, eyebrow="One question",
    text="“Can you show me your evaluation harness?”", sub="If the answer is a pause, you're looking at a prototype wearing production clothes."),
"root-cause-before-remediation": dict(layout="statement", dark=True, eyebrow="Escalations",
    text="Root cause first. Remediation second.", sub="Resize before you understand and you have the same problem at a higher bill."),
"the-dashboard-that-got-applause": dict(layout="statement", dark=False, eyebrow="Foundations",
    text="Build the engine before you shape the body.", sub="Dashboards that get applause are the cheapest thing to build and the most expensive thing to keep."),
"the-agent-inherits-the-user-s-permissions": dict(layout="statement", dark=True, eyebrow="Security",
    text="The agent inherits the user's permissions, and never exceeds them.", sub="Governance isn't the brake. It's what lets you take your foot off it."),
"where-i-put-the-human": dict(layout="numbered", dark=False, eyebrow="Healthcare",
    text="Two rules that held a clinical system together",
    items=["Never destroy the source. The original evidence stays, alongside anything derived from it.",
           "Never blur what was observed with what was inferred. Provenance is the difference between a record and a rumour."]),
# ---- next 18 ----
"a-landing-zone-is-a-political-document": dict(layout="statement", dark=True, eyebrow="Cloud platforms",
    text="A landing zone is a political document that happens to be implemented in Azure.", sub="Ownership, funding, exceptions, review. The Bicep sits underneath that page."),
"the-cheapest-migration-is-the-one-you-skip": dict(layout="bignum", dark=False, eyebrow="Migration",
    num="1/3", text="of the application estate had no owner. You don't migrate that. You retire it, or you ask the question out loud first."),
"three-questions-before-any-ai-project": dict(layout="numbered", dark=True, eyebrow="Before the model",
    text="Three questions before any AI project",
    items=["Who is accountable when it's wrong?","What is it allowed to see, per user, enforced by the platform?","What does a run cost at ten times the volume?"]),
"cost-per-run-is-an-architecture-decision": dict(layout="contrast", dark=False, eyebrow="Economics",
    text="A license costs the same whether people use it or not. An agent costs more the better it works.",
    cols=[("Fixed cost software",["Adoption is the goal","Cost is flat","Finance sees it once"]),
          ("Agentic systems",["Adoption is the goal","Cost scales with success","Token budgets per run","Model routing and caching","Cost next to quality on one dashboard"])]),
"where-deals-actually-die": dict(layout="statement", dark=True, eyebrow="Partner channel",
    text="Deals rarely die in the sales meeting. They die in the gap between the slide and the delivery calendar.", sub="The most expensive sentence in enterprise technology is “we'll figure that out in delivery.”"),
"retrieval-is-not-memory": dict(layout="contrast", dark=True, eyebrow="Agent design",
    text="Retrieval is not memory.",
    cols=[("Retrieval",["Looked up when needed","Source stays governed","Changes when the source changes","Provenance attached"]),
          ("Memory",["A second copy","Nobody governs it","Nobody knows when it's stale","The agent prefers it anyway"])]),
"write-the-runbook-before-the-incident": dict(layout="statement", dark=False, eyebrow="Resilience",
    text="Three confident answers about the failover. None matched what was configured.", sub="Assumed posture and actual posture drift apart quietly. Write it down and test it."),
"fabric-changed-the-question": dict(layout="contrast", dark=False, eyebrow="Data platforms",
    text="Fabric changed the question.",
    cols=[("Before",["“Where is the data?”","Catalogues and tribal knowledge","Every extract is a new place","Never really ends"]),
          ("After",["“Who owns this layer?”","Bronze: whoever ingests","Silver: the data team, with contracts","Gold: the people who consume it"])]),
"idempotent-or-it-didn-t-happen": dict(layout="statement", dark=True, eyebrow="Agent writes",
    text="Idempotent, or it doesn't get a tool.", sub="The demo never shows the retry. Production always does."),
"a-migration-is-a-change-of-ownership": dict(layout="numbered", dark=False, eyebrow="Migration",
    text="A migration is a change of ownership. Cutover is one milestone inside it.",
    items=["Who owns the bill, and from what date","Who owns change, and how it's made safely","Who owns the 3am page","When each handover happens. A date, not “after go-live”"]),
"the-cost-of-seeing-everything": dict(layout="statement", dark=True, eyebrow="Security operations",
    text="“Send everything to Sentinel” is a bill, not a security strategy.", sub="Start from what you need to detect. Trace backwards to the sources that feed it."),
"small-models-big-boundaries": dict(layout="contrast", dark=False, eyebrow="Model routing",
    text="Small models, big boundaries.",
    cols=[("Small, fast model",["Classify the request","Extract the fields","Format the answer","Pick the tool"]),
          ("Frontier model",["Reconcile conflicting evidence","Plan a multi-step task","Decide “I can't do this safely”"])]),
"the-pilot-that-never-ends": dict(layout="statement", dark=True, eyebrow="AI pilots",
    text="Most AI pilots don't fail. They just never end.", sub="Exit criteria go in the first document, before the architecture. Both outcomes are wins."),
"what-building-on-aws-taught-me-about-boring": dict(layout="numbered", dark=False, eyebrow="Solo operations",
    text="What keeps a platform running when you're the whole team",
    items=["Managed services wherever one exists","One deployment path, scripted, used every time","Backups tested by restoring them","A cost alarm set lower than you think you need","Logs you actually read"]),
"the-slide-nobody-wants-to-see": dict(layout="statement", dark=False, eyebrow="Assessments",
    text="In every assessment there's one slide people would rather not see.", sub="The dependency map. Every application, integration, identity, vendor, and data flow, on one page."),
"why-did-it-do-that": dict(layout="contrast", dark=True, eyebrow="Observability",
    text="Logs tell you what an agent did. A trace tells you why.",
    cols=[("Logs",["Tool was called","Response came back","Answer was returned"]),
          ("Traces",["The plan it formed","What it retrieved, and ignored","Each decision and the rejected alternative","The cost of every step"])]),
"boring-is-a-feature": dict(layout="statement", dark=False, eyebrow="Architecture",
    text="The platform should be dull. The product on top of it should be interesting.", sub="Most teams get that backwards."),
"what-i-m-carrying-into-next-year": dict(layout="numbered", dark=True, eyebrow="Year end",
    text="Three things I'm carrying into next year",
    items=["Write the rules down.","Keep the human where the judgment is.","Build the foundation before the feature."]),
}
